### ISSUE TITLE
Dry Run disables extruder permanently

### ISSUE THREAD

**Issue by adwsail** [OllisGit/OctoPrint-DryRun#2]
I enabled dry run on my ramps 1.6/mega2560/klipper and it worked great when I check the dry run box. However since doing so I am unable to extrude anything after unchecking the box. I even uninstalled it and still no extruder. In fact in octoprint I send in terminal G1 E50 F100 and what shows on the screen is just G1 F100. Uninstalling dry run fixed that but still no extruder. Ive swapped out the driver board and still the same. I tested the motor on the x axis and it works just fine. There is not even any power on the motor pins. Reboots, power down, etc all fail to restart the extruder. My extruder min temp is 20C and max extruder is set to 100. Its as though the extruder is disabled in firmware somewhere. Any ideas?

**Comment by OllisGit** [comment]
Hi @adwsail could you solved your problem?
After uninstalling the plugin, did you check the filesystem that the plugin was realy removed?

I could not reproduce this behavior.  
It is realy strange, because the plugin only filters G-Code that is send from Octoprint to the printer. It didn't send any flags/settings to the firmware.

Is extrusion possible with the (hardware based) Printer-Control Panel?

**Comment by adwsail** [comment]
My apologies, it turned out to be a bad ramps board, no power on the
extruder port. A new board and all is well, including Dry Run! Handy
program for diagnostics.

**Comment by OllisGit** [comment]
@adwsail  Good to know that you found the issue!
