### ISSUE TITLE
Feature Suggestion: Jump to layer

### ISSUE THREAD

**Issue by RootUser3885** [OllisGit/OctoPrint-DryRun#7]
A nice dry run feature would be to jump to a specific layer. Currently I edit the GCODE manually so it skips directly to that layer. This would be especially handy for testing a long dual extrusion print for jumping to layers of concern.

**Comment by OllisGit** [comment]
Hi @RootUser3885,

how do you edit the gcode?

Because I can skip all lines until the predefined layer line appears, but then the head is maybe in the wrong position.
In gcode the movement could be done in absolute or relative commands. 

So, the plugin must calculate the position internally and if the layer is reached it must move the extruder to the last position in an absolute movement, right?

**Comment by OllisGit** [comment]
No feedback -> closed!
